# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Notes
tagline:          'A Jekyll theme'
description:      'Writing and commentaries'
url:              "http://vant266.github.io"
baseurl:          /

author:
  name:
  url:

paginate:         5
plugins: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
