# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Penis
tagline:          'A Jekyll theme'
description:      'Writing and commentaries on statistical practice, machine learning,
                    algorithm design, and mathematical puzzles.'
url:              "http://vant266.github.io"
baseurl:          /

author:
  name:
  url:

paginate:         5
gems: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
